name: Publish Sub-splits

on:
  push:
    branches:
      - main
      - version/2.0
  create:
    tags:
      - '*'
  delete:
    tags:
      - '*'
jobs:
  publis_sub_splits:
    runs-on: ubuntu-latest
    name: Publish Sub-split
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: frankdejonge/use-github-token@1.0.1
        with:
          authentication: 'username:${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          user_name: 'Frank de Jonge'
          user_email: 'info@frenky.net'
      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v2
        with:
          path: './.splitsh'
          key: '${{ runner.os }}-splitsh'
      - uses: frankdejonge/use-subsplit-publish@1.0.0-beta.2
        with:
          source-branch: 'main'
          config-path: './config.subsplit-publish.json'
          splitsh-path: './.splitsh/splitsh-lite'
          splitsh-version: 'v1.0.1'
